//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackathonProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HackathonEntities1 : DbContext
    {
        public HackathonEntities1()
            : base("name=HackathonEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllHous> AllHouses { get; set; }
        public virtual DbSet<AllUser> AllUsers { get; set; }
        public virtual DbSet<Request_HIG> Request_HIGs { get; set; }
        public virtual DbSet<Request_LIG> Request_LIGs { get; set; }
        public virtual DbSet<Request_MIG> Request_MIGs { get; set; }
        public virtual DbSet<Result_HIG> Result_HIGs { get; set; }
        public virtual DbSet<Result_LIG> Result_LIGs { get; set; }
        public virtual DbSet<Result_MIG> Result_MIGs { get; set; }
    }
}
